apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhbk-pgsql-backend-creds
  namespace: rhbk
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rhbk-pgsql-backend-creds
    namespace: rhbk
  data:
    - secretKey: password
      remoteRef:
        key: pgsql-dev
        property: password
    - secretKey: username
      remoteRef:
        key: pgsql-dev
        property: username
    - secretKey: db_host
      remoteRef:
        key: pgsql-dev
        property: db_url